Web/Areas/Products/Controllers/PartialController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Total.Framework;
using Total.Helpers;

namespace Total.Web.Areas.Products.Controllers
{
    [ChildActionOnly]
    public class PartialController : Controller
    {
        private TotalDbContext _context;

        public PartialController() : this(new TotalDbContext())
        {}

        public PartialController(TotalDbContext context)
        {
            _context = context;
        }

        public ActionResult FeaturedItems()
        {
            var products = _context.Products.Where(p => !p.Deleted && p.Featured).OrderBy(p => Guid.NewGuid()).Include(p => p.ProductMeta).Take(8).ChunkData(2);
            return View("SmallProductGrid", products);
        }

        public ActionResult BestSellers()
        {
            var products = _context.Products.Where(p => !p.Deleted).OrderBy(p => p.OrderItems.Sum(oi => oi.Quantity)).Include(p => p.ProductMeta).Take(2);
            return View("TinyProduct", products);
        }

        public ActionResult NewItems()
        {
            var products = _context.Products.Where(p => !p.Deleted).OrderByDescending(p => p.CreatedDateTime).Include(p => p.ProductMeta).Take(2);
            return View("TinyProduct", products);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
                _context = null;
            }
            base.Dispose(disposing);
        }
    }
}

Web/Controllers/GenericController.cs
using System.Linq;
using System.Web.Mvc;
using Total.Framework;

namespace Total.Web.Controllers
{
    public class GenericController : Controller
    {

        private TotalDbContext _context;

        public GenericController() : this(new TotalDbContext())
        {}

        public GenericController(TotalDbContext context)
        {
            _context = context;
        }

        [ChildActionOnly]
        public ActionResult PrimaryNavigation()
        {
            var categories = _context.Categories.Where(c => !c.ParentCategoryId.HasValue).OrderBy(c => c.SortOrder);
            return View("Partials/_PrimaryNavigation", categories);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
                _context = null;
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/Shared/_SiteFooter.cshtml
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4 class="h4">Connect with us</h4>
                <p>Southfield House, Bourne, PE10 0FF</p>
                <p>+44 (0)1778 426661</p>
                <p><a href="#">hello@totalsolutionsgroup.co.uk</a></p>
                <p class="social">
                    <a href="#"><i class="fa fa-facebook-square"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-google-plus-square"></i></a>
                    <a href="#"><i class="fa fa-linkedin-square"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-youtube-play"></i></a>
                </p>
            </div>
            <div class="col-md-3">
                <h4 class="h4">Best Sellers</h4>
                @Html.Action("BestSellers", "Partial", new { area = "Products" })
            </div>
            <div class="col-md-3">
                <h4 class="h4">New Items</h4>
                @Html.Action("NewItems", "Partial", new { area = "Products" })
            </div>
            <div class="col-md-3">
                <h4 class="h4">Support</h4>
                
                <ul>
                    <li><a href="#">Terms &amp; Conditions</a></li>
                    <li><a href="#">Delivery</a></li>
                    <li><a href="#">Secure Payment</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">Refunds</a></li>
                    <li><a href="#">Track Orders</a></li>
                    <li><a href="#">Services</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Web/Views/Shared/_SiteHeader.cshtml
<header class="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="user-info">
                    <h4>Welcome back <a href="#">Michael</a>!</h4>
                </div>
            </div><!-- /col-md-4 -->
            <div class="col-md-4 text-center">
                <img src="/assets/img/total-ecommerce-logo.png" alt="Total Ecommerce" />
            </div>
            <div class="col-md-4">
                <div class="search">
                    <input type="search" class="form-control" placeholder="Search" />
                    <i></i>
                </div>
            </div><!-- /col-md-4 -->
        </div><!-- /row -->
    
        @Html.Action("PrimaryNavigation", "Generic", new { area = string.Empty })
    </div><!-- /container -->
</header><!-- /site-header --> 